function FileData_Pairs(x)
{
x.t("library","listed");
x.t("library","overview");
x.t("library","1.1");
x.t("library","models");
x.t("2008","2013");
x.t("scalable","network");
x.t("table","1-1");
x.t("type","section");
x.t("listed","table");
x.t("list","models");
x.t("network","technologies");
x.t("network","management");
x.t("simple","network");
x.t("overview","model");
x.t("name","model");
x.t("1.1","list");
x.t("number","simple");
x.t("2013","scalable");
x.t("section","number");
x.t("section","2.1");
x.t("models","library");
x.t("models","described");
x.t("models","model");
x.t("described","network");
x.t("protocol","(snmp)");
x.t("model","library");
x.t("model","type");
x.t("model","name");
x.t("management","library");
x.t("management","section");
x.t("management","protocol");
x.t("management","model");
x.t("2.1","2008");
x.t("1-1","table");
x.t("1-1","network");
x.t("(snmp)","network");
}
