function FileData_Pairs(x)
{
x.t("2008","2013");
x.t("scalable","network");
x.t("describes","features");
x.t("sections","simple");
x.t("consists","following");
x.t("network","technologies");
x.t("network","mangement");
x.t("network","management");
x.t("simple","network");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("2013","scalable");
x.t("chapter","describes");
x.t("scenarios","network");
x.t("configuration","requirements");
x.t("models","consists");
x.t("models","network");
x.t("models","chapter");
x.t("mangement","models");
x.t("protocol","(snmp)");
x.t("management","models");
x.t("management","protocol");
x.t("following","sections");
x.t("statistics","scenarios");
x.t("(snmp)","2008");
}
