function FileData_Pairs(x)
{
x.t("notes","exata");
x.t("notes","document");
x.t("notes","page");
x.t("2008","2013");
x.t("scalable","network");
x.t("5.1","release");
x.t("exata","5.1");
x.t("exata","2.0.1");
x.t("exata","3.1");
x.t("exata","release");
x.t("exata","4.1");
x.t("exata","described");
x.t("exata","2.1");
x.t("exata","2.2");
x.t("sections","section");
x.t("document","contains");
x.t("2.0.1","release");
x.t("3.1","release");
x.t("network","technologies");
x.t("2013","scalable");
x.t("release","notes");
x.t("section","exata");
x.t("4.1","release");
x.t("page","2008");
x.t("page","section");
x.t("described","following");
x.t("following","sections");
x.t("2.1","release");
x.t("2.2","release");
x.t("contains","release");
}
