function FileData_Pairs(x)
{
x.t("library","consists");
x.t("privacy","ctr");
x.t("2008","2013");
x.t("scalable","network");
x.t("describes","features");
x.t("layer","models");
x.t("cyber","model");
x.t("wired","equivalent");
x.t("mac","layer");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("equivalent","privacy");
x.t("cbc-mac","protocol");
x.t("ctr","cbc-mac");
x.t("2013","scalable");
x.t("chapter","describes");
x.t("section","wired");
x.t("scenarios","mac");
x.t("configuration","requirements");
x.t("models","cyber");
x.t("models","mac");
x.t("models","chapter");
x.t("protocol","2008");
x.t("model","library");
x.t("following","section");
x.t("statistics","scenarios");
}
