function FileData_Pairs(x)
{
x.t("library","consists");
x.t("2008","2013");
x.t("scalable","network");
x.t("describes","features");
x.t("multi-layer","models");
x.t("support","(satellite-rsv)");
x.t("sections","aloha");
x.t("aloha","satellite");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("2013","scalable");
x.t("chapter","describes");
x.t("scenarios","multi-layer");
x.t("configuration","requirements");
x.t("satellite","model");
x.t("models","multi-layer");
x.t("models","chapter");
x.t("models","satellite");
x.t("rsv","support");
x.t("model","library");
x.t("model","rsv");
x.t("following","sections");
x.t("statistics","scenarios");
x.t("(satellite-rsv)","2008");
}
