function FileData_Pairs(x)
{
x.t("protocols","modeled");
x.t("2008","2013");
x.t("scalable","network");
x.t("describes","protocols");
x.t("describes","architecture");
x.t("exata","simulator");
x.t("exata","section");
x.t("modeled","exata");
x.t("details","discrete-event");
x.t("simulator","2008");
x.t("simulator","basics");
x.t("simulator","section");
x.t("3.1","provides");
x.t("network","technologies");
x.t("overview","discrete-event");
x.t("3.2","describes");
x.t("3.3","provides");
x.t("3.4","describes");
x.t("provides","overview");
x.t("provides","implementation");
x.t("discuss","basics");
x.t("2013","scalable");
x.t("chapter","discuss");
x.t("basics","exata");
x.t("basics","simulator");
x.t("basics","chapter");
x.t("section","3.1");
x.t("section","3.2");
x.t("section","3.3");
x.t("section","3.4");
x.t("discrete-event","simulation");
x.t("architecture","exata");
x.t("implementation","details");
x.t("simulation","exata");
x.t("simulation","section");
}
