function FileData_Pairs(x)
{
x.t("coding","guidelines");
x.t("appendix","provides");
x.t("2008","2013");
x.t("scalable","network");
x.t("converting","models");
x.t("platforms","coding");
x.t("platforms","appendix");
x.t("platforms","2008");
x.t("platforms","discusses");
x.t("exata","models");
x.t("32-bit","64-bit");
x.t("network","technologies");
x.t("guidelines","developing");
x.t("guidelines","64-bit");
x.t("discusses","compatibility");
x.t("provides","coding");
x.t("developing","exata");
x.t("issues","converting");
x.t("2013","scalable");
x.t("64-bit","platforms");
x.t("compatibility","issues");
x.t("models","32-bit");
x.t("models","64-bit");
}
